### ISSUE TITLE
CatsV2

### ISSUE THREAD

**Issue by alf-wangzhi** [HaoLi12345/CATS#1]
May I kindly ask if you could please share the code for v2?

**Comment by HaoLi12345** [comment]
Oh sorry, I will update it ASAP. Thanks


Hao Li

On Aug 17, 2023, at 12:37 AM, alf-wangzhi ***@***.***> wrote:

﻿

May I kindly ask if you could please share the code for v2?

**Comment by alf-wangzhi** [comment]
I apologize for the interruption. The code for v2 is missing the following modules: "from .cats_swin import SwinTransformer, PatchMerging, PatchMergingV2."

**Comment by HaoLi12345** [comment]
should be good now, let me know any issues :)
